#!/usr/bin/perl -Tw

# $Id: quickform,v 1.10 2000/04/06 22:02:55 root Exp root $

# Copyright (c) Mark Summerfield 1999-2000. All Rights Reserved.
# May be used/distributed under the GPL.

# WARNING - this program is provided as an example of QuickForm use and not as
# an example of production quality CGI code - it may not be secure. 

use strict ;

use CGI qw( :standard :html3 ) ;
use CGI::QuickForm qw( show_form colour ) ;

my $STYLE_FIELDVALUE = 'style="background-color:#DDDDDD"' ;

show_form(
    -MULTI_COLUMN     => 1, # MULTI_COLUMN
    -TITLE            => 'Test Form',
    -ACCEPT           => \&on_valid_form, 
    -SIZE             => 25,
    -SPACE            => 1,
    -CHECK            => ( query_string() =~ /QFCHK=0/o ? 0 : 1 ), 
    -FOOTER           => qq{<a href="} . 
                         url() . #"
                         qq{?QFCHK=0\&Age=28\&Surname=Bloggs\&Forename=Freda">} . #"
                         qq{Defaults</a>} . 
                         end_html,
    -BUTTONS          => [ { -name => 'Add' }, { -name => 'Del' } ],
    -STYLE_BUTTONS    => 'center',
    -STYLE_FIELDNAME  => 'style="background-color:#AAAAAA"',
    -STYLE_FIELDVALUE => $STYLE_FIELDVALUE,
    -STYLE_WHY        => 'style="font-style:italic;color:red"',
    -STYLE_DESC       => 'style="color:darkblue"',
    -VALIDATE  => sub { ( int rand(2), "<P>" . colour( 'RED', 'Randomly Invalid' ) ) },
    -FIELDS           => [
        {
            -LABEL      => 'Forename',
            -CLEAN      => \&cleanup, 
            -VALIDATE   => sub { 
                            my $valid = length shift > 3 ; 
                            ( $valid, 'Name too short' ) ;
                        }
        },
        {
            -LABEL      => 'Surname',
            -END_ROW    => 1, # MULTI_COLUMN
            -CLEAN      => \&cleanup, 
            -REQUIRED   => 1,
            -VALIDATE   => sub { 
                                my $valid = length shift > 3 ; 
                                ( $valid, 'Name too short' ) ;
                            }
        },
        {
            -LABEL      => 'Sex',
            -TYPE       => 'radio_group',
            '-values'   => [ qw( Female Male ) ],
        },
        {
            -LABEL      => 'Age',
            -END_ROW    => 1, # MULTI_COLUMN
            -VALIDATE   => &mk_valid_number( 3, 130 ), 
            -size       => 10,
        },
        { 
            -LABEL     => 'Hair colour', 
            -REQUIRED  => undef,
            -TYPE      => 'scrolling_list',
            -VALIDATE  => undef,
            -name      => undef, # Defaults to -LABEL's value.
            '-values'  => [ qw( Red Black Brown Grey White ) ],
            -size      => 1,
            -multiples => undef,
        },
        { 
            -LABEL     => 'Password', 
            -END_ROW   => 1, # MULTI_COLUMN
            -REQUIRED  => undef,
            -TYPE      => 'password_field',
            -VALIDATE  => undef,
            -name      => undef, # Defaults to -LABEL's value.
            -value     => undef,
            -size      => 10,
            -maxlength => undef,
        },
        { 
            -LABEL     => 'Address', 
            -END_ROW   => 1,
            -STYLE_FIELDVALUE => qq{$STYLE_FIELDVALUE colspan="3"}, # MULTI_COLUMN
            -REQUIRED  => undef,
            -TYPE      => 'textarea',
            -VALIDATE  => undef,
            -name      => undef, # Defaults to -LABEL's value.
            -default   => undef,
            -rows      => 3,
            -columns   => 40,
        },
        { 
            -LABEL     => 'Worst Sport', 
            -REQUIRED  => undef,
            -TYPE      => 'radio_group',
            -STYLE_FIELDVALUE => qq{$STYLE_FIELDVALUE colspan="3"}, # MULTI_COLUMN
            -VALIDATE  => undef,
            -name      => undef, # Defaults to -LABEL's value.
            '-values'  => [ qw( Boxing Cricket Golf ) ], 
            -default   => 'Golf',
            -size      => undef,
            -multiples => undef,
        },
    ],
) ;


sub cleanup {
    local $_ = shift ; # This is the value of param( <fieldname> )

    tr/\t \n\r\f/ /s ; # Convert multiple whitespace to one space.
    s/^\s*//o ; # Remove leading whitespace.
    s/\s*$//o ; # Remove trailing whitespace.

    $_ ;
}


sub on_valid_form {

    my @keys = param ;

    # Process the data in some way, e.g. save it to a file or database.

    print
        header,
        start_html( 'Test Form Data Accepted' ),
        h3( 'Test Form Data Accepted' ),
        p( "Thank you ", param( 'Forename' ), " for your data." ),
        ;
    print qq{<table border="0">} ;
    local $_ ;
    foreach( @keys ) {
        print "<tr><td>$_</td><td>", param( $_ ), "</td></tr>" ;
    }
    print "</table><p /><hr />" ;
}


sub mk_valid_number {
    my( $min, $max ) = @_ ;

    sub { 
        my $valid = $_[0] ? ( $min <= $_[0] and $_[0] <= $max ) : 1 ;
        ( $valid, "Number should be between $min and $max inclusive" ) ;
    } ;
}

